Postgres collector public integration
logzio/postgres-collector pull request #2
Opened 2022-02-17 09:37 UTC by yotamloe

* Ability to add custom queries
* Ability to collect metrics from multiple instances
* Ability to add custom labels per instance

2022-03-02 16:12 UTC, Doron-Bargo requested changes
looking good - please look on my commnets

2022-03-02 16:12 UTC, Doron-Bargo commented on README.md
> +logzio/mobileye-rds-collector
why its called mobileye?

2022-03-02 16:12 UTC, Doron-Bargo commented on README.md
> +logzio/mobileye-rds-collector
why its called mobileye?

2022-03-03 08:47 UTC, yotamloe commented on README.md
>  | LOGZIO_REGION (Required)| Your Logz.io region code. For example if your region is US, then your region code is `us`. You can find your region code here: https://docs.logz.io/user-guide/accounts/acc
We have a [function](https://github.com/logzio/postgres-rds-collector/blob/mobileye/config.py#L50-L62) that generates the listener URL based on this input, that's was the approach in previous integrations like cloudwatch-metrics. I can easily remove this if you think that the correct approach

2022-03-03 11:22 UTC, yotamloe commented on Dockerfile
>  COPY otelcontribcol_linux_amd64 otelcontribcol_linux_amd64
Done

2022-03-06 16:22 UTC, Doron-Bargo approved these changes
lgtm

2022-03-07 08:59 UTC, merged